#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="1.4.4"

dl http://punbb.informer.com/download/punbb-${VERSION}.tar.gz /usr/local/src

