#!/bin/sh -ex

DB_NAME=punbb
DB_USER=punbb
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/punbb

# unpack and set permissions
unzip $SRC/punbb-*.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/punbb-* $WEBROOT
rm $SRC/punbb-*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/img/avatars

# configure apache
a2dissite default
a2ensite punbb
a2enmod rewrite

