#!/bin/sh -ex

DB_NAME=punbb
DB_USER=punbb
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/punbb

# unpack and set permissions
tar -zxf $SRC/punbb-*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/punbb-* $WEBROOT
rm $SRC/punbb-*.tar.gz

chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/img/avatars

# configure apache
a2dissite 000-default
a2ensite punbb
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/admin/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL $URL --data "form_sent=1&req_db_type=mysqli&req_db_host=localhost&req_db_name=$DB_NAME&db_username=$DB_USER&db_password=$DB_PASS&db_prefix=&req_email=$EMAIL&req_username=$ADMIN_NAME&req_password1=$ADMIN_PASS&req_base_url=http%3A%2F%2F127.0.0.1&req_language=English&start=Start+install"

rm -f /tmp/cookie

# create config and secure
CONF=$WEBROOT/config.php
mv $SRC/config.php.tmpl $CONF
sed -i "s|db_name.*|db_name = '$DB_NAME';|" $CONF
sed -i "s|db_username.*|db_username = '$DB_USER';|" $CONF
sed -i "s|db_password.*|db_password = '$DB_PASS';|" $CONF
sed -i "s|\$base_url.*|//\$base_url = 'http://$DOMAIN';|" $CONF


chown www-data:www-data $CONF
chmod 640 $CONF

# set title
$MYSQL_BATCH --execute "UPDATE $DB_NAME.config SET conf_value=\"TurnKey PunBB\" WHERE conf_name=\"o_board_title\";"

# stop services
service mysql stop
service apache2 stop

