#!/bin/bash -e
# regenerate punbb secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/punbb/config.php

COOKIE=$(mcookie | cut --bytes 1-6)
sed -i "s|cookie_name.*|cookie_name = 'forum_cookie_$COOKIE';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|db_password.*|db_password = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=punbb --pass="$PASSWORD"

