#!/bin/bash -e
# set punbb admin password, email and domain to serve

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/punbb.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"

